### PR TITLE
SG-424: Fix go dependencies in panasas-dev branch for minio

### PR DESCRIPTION
**Pull request by akhmialeuski**
## Description

Updated go mod dependencies. `github.com/minio/pkg` has been replaced with `github.com/panasasinc/minio-pkg@15e7125ba889821ddadb4bedf83002ea6dcc5578` from panasas minio-pkg fork.

Updated "Staging" job, removed `nancy` which not used in the upstream repository

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

### CODE REVIEW

**Comment by dmitrizpanasas** [comment]
As I see staging workflow is still failing. So maybe it makes sense to update building process to use out go proxy server?

**Comment by yauhen-matsiushonak** [comment]
@dmitrizpanasas , the problem that we still try to use upstream minio packages instead of panasas fork. Maybe this is a right time to finally make a full fork and rename packages?

**Comment by dmitrizpanasas** [comment]
> @dmitrizpanasas , the problem that we still try to use upstream minio packages instead of panasas fork. Maybe this is a right time to finally make a full fork and rename packages?

So we need to rename `minio/minio => panasasinc/minio` `minio/pkg => panasasinc/minio-pkg` and the same for `mc`, `minio-go`, right?

The only thing here - most likely the `minio/pkg` and some others packages still will leave in go.mod file as indirect dependencies even if we update these dependencies and update import statements - but that should be ok

**Comment by yauhen-matsiushonak** [comment]
Added @azepam and @defereq to the change.

@dmitrizpanasas , yes, I mean exactly renaming of all packages that we forked and import statements for them. Yes, this will be a bug change with tons of files in all our forked repositories, but in practice this may be the right way to go further, as minio never accept our vendor-specific changes, so we will need to maintain our fork anyways.

Unless @defereq  or @azepam can suggest some more elegant solution for this problem.

**Comment by azepam** [comment]
[Let's have a look on it](https://github.com/golang/go/wiki/Modules#when-should-i-use-the-replace-directive). I've never used it for replacing to fork, but it works fine for updating packages, and according to documentation it should work with replacing to forks.

**Comment by akhmialevskiy** [comment]
>

**Comment by akhmialeuski** [comment]
> @dmitrizpanasas , yes, I mean exactly renaming of all packages that we forked and import statements for them. Yes, this will be a bug change with tons of files in all our forked repositories, but in practice this may be the right way to go further, as minio never accept our vendor-specific changes, so we will need to maintain our fork anyways.

In addition to this, we need to install our versions for `minio-mc` and `minio-pkg` otherwise we will not be able to make a replacement.

**Comment by azepam** [comment]
According to the last build log, it looks good, and don't use original minio-pkg.
But should we replace all minio packages? If currently no - ok, I'll approve.

P.S. please fix typo in description(do mod => go mod)

**Review by azepam — APPROVED** [review]

**Pull request merged**
